
cuda is not avaiable.

==================================================
goal = test
device = cpu
device_id = 0
dataset = Cifar10_dir_0.3_imbalance_40
num_classes = 10
model_family = HtFE8
batch_size = 256
local_learning_rate = 0.06
use_decay_scheduler = False
learning_rate_decay = False
learning_rate_decay_gamma = 0.99
global_rounds = 200
edge_epochs = 1
local_epochs = 10
algorithm = FedSAE
join_ratio = 1.0
random_join_ratio = False
num_clients = 40
num_edges = 10
prev = 0
times = 1
eval_gap = 1
save_folder_name = temp
auto_break = False
feature_dim = 512
vocab_size = 98635
max_len = 200
client_drop_rate = 0.0
train_slow_rate = 0.0
send_slow_rate = 0.0
time_select = False
time_threthold = 10000
lamda = 2
trans_delay_simulate = False
agg_type = 0
buffersize = 10
test_useglclassifier = 0
gamma = 0.7
addTGP = False
use_beta = False
SAEbeta = 0.2
drawtsne = True
drawround = 10
noise_dim = 512
generator_learning_rate = 0.005
hidden_dim = 512
server_epochs = 100
alpha = 1.0
beta = 1.0
mentee_learning_rate = 0.005
T_start = 0.95
T_end = 0.98
server_learning_rate = 0.01
margin_threthold = 100.0
generator_path = stylegan/stylegan-xl-models/imagenet64.pkl
stable_diffusion_prompt = a cat
server_batch_size = 100
gen_batch_size = 4
mu = 50.0
==================================================
Random seed set as 42

============= Running time: 0th =============
Creating server and clients ...
FedAvgCNN(in_features=3, num_classes=args.num_classes, dim=1600)
torchvision.models.googlenet(pretrained=False, aux_logits=False, num_classes=args.num_classes)
mobilenet_v2(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet18(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet34(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet50(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet101(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet152(pretrained=False, num_classes=args.num_classes)
Traceback (most recent call last):
  File "main.py", line 498, in <module>
    run(args)
  File "main.py", line 235, in run
    server = FedSAE(args, i)
  File "/home/ubuntu/repos/SAE-FedProto-CEC/system/flcore/servers/serverSAE.py", line 31, in __init__
    self.set_clients(clientSAE)
  File "/home/ubuntu/repos/SAE-FedProto-CEC/system/flcore/servers/serverbase.py", line 102, in set_clients
    train_data = read_client_data(self.dataset, i, is_train=True)
  File "/home/ubuntu/repos/SAE-FedProto-CEC/system/utils/data_utils.py", line 33, in read_client_data
    train_data = read_data(dataset, idx, is_train)
  File "/home/ubuntu/repos/SAE-FedProto-CEC/system/utils/data_utils.py", line 11, in read_data
    with open(train_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/Cifar10_dir_0.3_imbalance_40/train/0.npz'
